### ISSUE TITLE
where can I download the dataset?

### ISSUE THREAD

**Issue by neouyghur** [penny9287/Hierarchical-Multiple-Features-Combination-Model#1]
Hi, this is an interesting project. I wonder where can I download the dataset? Thanks.

**Comment by penny9287** [comment]
Hello, thank you for your attention. The dataset is only assigned to the person who participated in the evaluation task of China Machine Translation Workshop (CWMT). The public Uyghur-Chinese dataset contains 50K parallel sentences, and you can download it here:  
[http://www.chineseldc.org/resource_list.php?begin=60&count=20](url)
But you will have to pay to use it.
